export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const TOGGLE_AUTH_STATE = "TOGGLE_AUTH_STATE";
export const LISTING_HOUSE = "LISTING_HOUSE";
export const CREATE_OTP = "CREATE_OTP";
export const VERIFY_OTP = "VERIFY_OTP";
export const TOGGLE_CREATE_STATE = "TOGGLE_CREATE_STATE";